apiVersion: v2
appVersion: v4.3.4.1
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 2.5.0
description: qBittorrent is a cross-platform free and open-source BitTorrent client
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
keywords:
- qbittorrent
- torrrent
kubeVersion: '>=1.16.0-0'
maintainers:
- email: jeff@billimek.com
  name: billimek
name: qbittorrent
sources:
- https://github.com/qbittorrent/qBittorrent
- https://github.com/k8s-at-home/container-images
version: 10.1.0
