apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "plex.fullname" . }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: {{ .Values.data.persistence.readOnly }}
            - mountPath: /config
              name: config
            - mountPath: /transcode
              name: transcode
          envFrom:
            - configMapRef:
                name: {{ include "plex.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: plex
              containerPort: 32400
              protocol: TCP
              {{- if and .Values.plex.hostPort.enabled }}
              hostPort: {{ .Values.plex.hostPort.port }}
              {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
{{- if and .Values.data.persistence.enabled .Values.data.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.data.persistence.existingClaim }}
            readOnly: {{ .Values.data.persistence.readOnly }}
{{- else if not .Values.data.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- end }}
{{- if and .Values.config.persistence.enabled .Values.config.persistence.existingClaim }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.config.persistence.existingClaim }}
{{- else if not .Values.config.persistence.enabled }}
        - name: config
          emptyDir: {}
{{- end }}
{{- if and .Values.transcode.persistence.enabled .Values.transcode.persistence.existingClaim }}
        - name: transcode
          persistentVolumeClaim:
            claimName: {{ .Values.transcode.persistence.existingClaim }}
{{- else if not .Values.transcode.persistence.enabled }}
        - name: transcode
          emptyDir: {}
{{- end }}
  volumeClaimTemplates:
{{- if and .Values.data.persistence.enabled (not .Values.data.persistence.existingClaim) }}
    - metadata:
        name: data
        labels:
          app: "{{ template "plex.name" . }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.data.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.data.persistence.size | quote }}
        {{ include "plex.data.storageClass" . }}
{{- end }}
{{- if and .Values.config.persistence.enabled (not .Values.config.persistence.existingClaim) }}
    - metadata:
        name: config
        labels:
          app: "{{ template "plex.name" . }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.config.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.config.persistence.size | quote }}
        {{ include "plex.config.storageClass" . }}
{{- end }}
{{- if and .Values.transcode.persistence.enabled (not .Values.transcode.persistence.existingClaim) }}
    - metadata:
        name: transcode
        labels:
          app: "{{ template "plex.name" . }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.transcode.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.transcode.persistence.size | quote }}
        {{ include "plex.transcode.storageClass" . }}
{{- end }}