apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
spec:
  chart: nextcloud 
  repo: https://nextcloud.github.io/helm/
  valuesContent: |-
    persistence:
      enabled: true
      storageClass: nfs-client
      accessMode: ReadWriteMany
