apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-helm-dashboard-route
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
  # 这里设置你的域名
    - match: Host(`nextcloud.k3s.com`)
      kind: Rule
      services:
        - name: nextcloud
          port: 8080
