apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
# replace with namespace where provisioner is deployed
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
     matchLabels:
        app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
       serviceAccountName: nfs-client-provisioner
       containers:
       - name: nfs-client-provisioner
         image: quay.io/external_storage/nfs-client-provisioner:latest
         volumeMounts:
         - name: nfs-client-root
           mountPath: /persistentvolumes
         env:
         - name: PROVISIONER_NAME
           value: fuseim.pri/ifs
         - name: NFS_SERVER
           value: 192.168.150.143
         - name: NFS_PATH
           value: /volume1/nfs
       volumes:
       - name: nfs-client-root 
         nfs:
           server: 192.168.150.143
           path: /volume1/nfs
