apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  volumeName: 
  storageClassName: nfs-client

