apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  labels:
    type: pv-test
spec:
  capacity:
    storage: 10Mi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/volume1/nfs/mysql"
    server: 192.168.150.143
    readOnly: false
