apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jumpserver
  labels:
    type: nfs
spec:
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/jumpserver"
    server: localhost
    readOnly: false
