apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    type: pv-mysql
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/volume1/nfs/mysql"
    server: 192.168.150.143
    readOnly: false
