kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: pv-wordpress
