apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  labels:
    type: pv-wordpress
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/wordpress"
    server: localhost
    readOnly: false
