annotations:
  artifacthub.io/changes: |
    - Add hostPath option for the data volume
  artifacthub.io/images: |
    - name: linuxserver/jellyfin
      image: docker.io/linuxserver/jellyfin:10.7.2-1-ls105
  artifacthub.io/license: MIT
apiVersion: v2
appVersion: 10.7.2-1-ls105
description: Jellyfin Helm chart that is based on linuxserver/jellyfin Docker image.
home: https://jellyfin.org
icon: https://utkuozdemir.org/helm-charts/jellyfin.png
keywords:
- jellyfin
- media-server
- streaming
- video
maintainers:
- email: uoz@protonmail.com
  name: Utku Özdemir
  url: https://utkuozdemir.org
name: jellyfin
sources:
- https://github.com/jellyfin/jellyfin
- https://github.com/utkuozdemir/helm-charts
type: application
version: 1.1.3
