apiVersion: v1
kind: PersistentVolume
metadata:
  name: inspect-pv
  labels:
    type: nfs001
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/inspect_log"
    server: localhost
    readOnly: false
