---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: "standard"
  nfs:
    path: /data/es/pv1
    server: localhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/es/pv2
    server: localhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: "standard"
  nfs:
    path: /data/es/pv3
    server: localhost
