apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jellyfin
spec:
  chart: jellyfin 
  repo: https://utkuozdemir.org/helm-charts
  valuesContent: |-
    persistence:
      data:
        enabled: true
        storageClass: nfs-client
      config:
        enabled: true
        storageClass: nfs-client
