version: '2.15'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:0.5.8-rc10
    ports:
      - 11434:11434
    volumes:
      - /Users/lihuimin/docker/ai/ollama:/root/.ollama

  web-ui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:v0.5.10
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
