apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: livego-live-route
spec:
  entryPoints:
    - web
  routes:
  # 这里设置你的域名
    - match: Host(livego.live.k3s.com`)
      kind: Rule
      services:
        - name: livego
          port: 1935
