apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    type: nfs
spec:
  storageClassName: storageclass-mysql
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/mysql"
    server: localhost
    readOnly: false
