apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zentao
  labels:
    type: nfs
spec:
  storageClassName: storageclass-zentao
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/zentao"
    server: localhost
    readOnly: false
